CREATE TABLE org (
    id UUID PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    pw_hash BYTEA NOT NULL,
    pw_salt BYTEA NOT NULL,
    pw_created TIMESTAMP WITH TIME ZONE NOT NULL,
    created TIMESTAMP WITH TIME ZONE NOT NULL
);